# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Solo - cheap audio recorder
email: solo@solo-system.com

description: Solo is an audio recorder.  Outdoor, continuous, battery-powered, based on raspberry-pi, open source, build-your-own, high-fidelity, configurable, user-servicable, cheap, modifiable, extensible, modular,

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: whatever
github_username:  solos-ystem

# Build settings
markdown: kramdown
